--
-- PostgreSQL database dump
--

-- Dumped from database version 9.3.11
-- Dumped by pg_dump version 9.3.11
-- Started on 2016-03-30 14:26:03 CEST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = wonders, pg_catalog;

--
-- TOC entry 2055 (class 0 OID 16809)
-- Dependencies: 177
-- Data for Name: Wonder; Type: TABLE DATA; Schema: wonders; Owner: wonders_user
--

INSERT INTO "Wonder" VALUES ('Colossus of Rhodes', 'Ancient', '{"ὁ Κολοσσὸς Ῥόδιος"}', 'The Colossus of Rhodes /roʊdz/ (Ancient Greek: ὁ Κολοσσὸς Ῥόδιος ho Kolossòs Rhódios)[1] was a statue of the Greek titan-god of the sun Helios, erected in the city of Rhodes, on the Greek island of the same name, by Chares of Lindos in 280 BC. One of the Seven Wonders of the Ancient World, it was constructed to celebrate Rhodes'' victory over the ruler of Cyprus, Antigonus I Monophthalmus, whose son unsuccessfully besieged Rhodes in 305 BC. Before its destruction in the earthquake of 226 BC, the Colossus of Rhodes stood over 30 metres (98 feet) high,[2] making it one of the tallest statues of the ancient world.[3]', 1, '(http://img06.deviantart.net/a7d0/i/2012/051/7/7/colossus_of_rhodes_by_pervandr-d4qcdti.jpg,f,t)', 0, NULL, '{}');
INSERT INTO "Wonder" VALUES ('Great Pyramids of Giza', 'Ancient', '{"Pyramid of Cheops"}', 'The Great Pyramid of Giza (also known as the Pyramid of Khufu or the Pyramid of Cheops) is the oldest and largest of the three pyramids in the Giza pyramid complex bordering what is now El Giza, Egypt. It is the oldest of the Seven Wonders of the Ancient World, and the only one to remain largely intact.', 2, '(http://toptenworld.net/wp-content/uploads/2014/04/great-pyramid-giza-1.jpg,f,t)', 0, 0, '{}');
INSERT INTO "Wonder" VALUES ('Machu Picchu', 'Ancient', '{"Machu Pikchu"}', 'Machu Picchu (in hispanicized spelling, Spanish pronunciation: [ˈmatʃu ˈpiktʃu]) or Machu Pikchu (Quechua machu old, old person, pikchu peak; mountain or prominence with a broad base which ends in sharp peaks,[1] "old peak", pronunciation [ˈmɑtʃu ˈpixtʃu]) is a 15th-century Inca site located 2,430 metres (7,970 ft) above sea level.[2][3] It is located in the Cusco Region, Urubamba Province, Machupicchu District in Peru.[4]', 3, '(http://www.travelandleisure.com/sites/default/files/styles/tnl_redesign_article_landing_page/public/1434385487/ATTRACTIONS0615-machu-picchu.jpg,f,t)', 0, 0, '{}');
INSERT INTO "Wonder" VALUES ('Petra', 'Ancient', '{Al-Batra,Πέτρα}', 'Petra (Arabic: البترا, Al-Batrāʾ; Ancient Greek: Πέτρα), originally known as Raqmu to the Nabataeans, is a historical and archaeological city in the southern Jordanian governorate of Maan that is famous for its rock-cut architecture and water conduit system. Another name for Petra is the Rose City due to the color of the stone out of which it is carved.', 4, '(https://anishashahbbc.files.wordpress.com/2012/10/samsung-pics-5416.jpg,f,t)', 0, 0, '{}');
INSERT INTO "Wonder" VALUES ('Temple of Artemis at Ephesus', 'Ancient', '{Ἀρτεμίσιον,"Artemis Tapınağı"}', 'The Temple of Artemis or Artemision (Greek: Ἀρτεμίσιον, Turkish: Artemis Tapınağı), also known less precisely as the Temple of Diana, was a Greek temple dedicated to the goddess Artemis. It was located in Ephesus (near the modern town of Selçuk in present-day Turkey). One of the Seven Wonders of the Ancient World, it was completely rebuilt three times before its eventual destruction in 401 AD.[1] Only foundations and sculptural fragments of the latest of the temples at the site remain.', 5, '(http://ephesusattractions.com/wp-content/uploads/temple-of-artemis-01.jpg,f,t)', 0, 0, '{}');
INSERT INTO "Wonder" VALUES ('Mausoleum at Halicarnassus', 'Ancient', '{"Μαυσωλείο της Αλικαρνασσού"}', 'The Mausoleum at Halicarnassus or Tomb of Mausolus [a] (Persian: آرامگاه هالیکارناسوس‎‎; Modern Greek: Μαυσωλείο της Αλικαρνασσού) was a tomb built between 353 and 350 BC at Halicarnassus (present Bodrum, Turkey) for Mausolus, a satrap in the Persian Empire, and his sister-wife Artemisia II of Caria. The structure was designed by the Greek architects Satyros and Pythius of Priene.[1][2]', 6, '(http://homepages.uel.ac.uk/u0902931/images/halicarnassus.jpg,f,t)', 0, 0, '{}');
INSERT INTO "Wonder" VALUES ('Lighthouse of Alexandria', 'Ancient', '{"ὁ Φάρος τῆς Ἀλεξανδρείας"}', 'The Lighthouse of Alexandria, sometimes called the Pharos of Alexandria (/ˈfɛərɒs/; Ancient Greek: ὁ Φάρος τῆς Ἀλεξανδρείας), was a lighthouse built by the Ptolemaic Kingdom between 280 and 247 BC which was between 393 and 450 ft (120 and 137 m) tall. One of the Seven Wonders of the Ancient World, it was one of the tallest man-made structures in the world for many centuries. Badly damaged by three earthquakes between AD 956 and 1323, it then became an abandoned ruin. It was the third longest surviving ancient wonder (after the Mausoleum at Halicarnassus and the extant Great Pyramid of Giza) until 1480, when the last of its remnant stones were used to build the Citadel of Qaitbay on the site. In 1994, French archaeologists discovered some remains of the lighthouse on the floor of Alexandria''s Eastern Harbour.[1] The Ministry of State of Antiquities in Egypt has planned, as of late 2015, to turn submerged ruins of ancient Alexandria, including those of the Pharos, into an underwater museum.[2]', 7, '(https://cdn.thinglink.me/api/image/657288420896276480/1240/10/scaletowidth,f,t)', 0, 0, '{}');
INSERT INTO "Wonder" VALUES ('The Hanging Gardens of Babylon', 'Ancient', '{""}', 'The Hanging Gardens of Babylon, one of the Seven Wonders of the Ancient World, is the only one whose location has not been definitively established.[1]', 8, '(http://s2.thingpic.com/images/Sa/edepRdsEfP2x4Pe8kh6ikPYV.jpeg,f,t)', 0, 0, '{}');
INSERT INTO "Wonder" VALUES ('Statue of Zeus at Olympia', 'Ancient', '{""}', 'The Statue of Zeus at Olympia was a giant seated figure, about 13 m (43 ft) tall,[1] made by the Greek sculptor Phidias around 435 BC at the sanctuary of Olympia, Greece, and erected in the Temple of Zeus there. A sculpture of ivory plates and gold panels over a wooden framework, it represented the god Zeus sitting on an elaborate cedar wood throne ornamented with ebony, ivory, gold and precious stones. One of the Seven Wonders of the Ancient World,[2] it was lost and destroyed during the 5th century AD with no copy ever being found, and details of its form are known only from ancient Greek descriptions and representations on coins.', 9, '(http://wanderlord.com/wp-content/uploads/2014/12/Statue-of-Zeus.jpg,f,t)', 0, 0, '{}');
INSERT INTO "Wonder" VALUES ('Chichen itza', 'Ancient', '{"Chichén Itzá"}', 'Chichen Itza, "at the mouth of the well of the Itza") was a large pre-Columbian city built by the Maya people of the Terminal Classic period. The archaeological site is located in Tinúm Municipality, Yucatán State, Mexico.[3]', 10, '(http://i1.trekearth.com/photos/39379/dsc0779.jpg,f,t)', 0, 0, '{}');
INSERT INTO "Wonder" VALUES ('Taj Mahal', 'Ancient', '{""}', 'The Taj Mahal is an ivory-white marble mausoleum on the south bank of the Yamuna river in the Indian city of Agra. It was commissioned in 1632 by the Mughal emperor, Shah Jahan, to house the tomb of his favorite wife, Mumtaz Mahal.', 13, '(http://www.tajmahal.org.uk/gifs/taj-mahal.jpeg,f,t)', 0, 0, '{}');
INSERT INTO "Wonder" VALUES ('Colosseum', 'Ancient', '{"Amphitheatrum Flavium","Anfiteatro Flavio",Colosseo}', 'The Colosseum or Coliseum (/kɒləˈsiːəm/ kol-ə-see-əm), also known as the Flavian Amphitheatre (Latin: Amphitheatrum Flavium; Italian: Anfiteatro Flavio [amfiteˈaːtro ˈflaːvjo] or Colosseo [kolosˈsɛːo]), is an oval amphitheatre in the centre of the city of Rome, Italy. Built of concrete and sand,[1] it is the largest amphitheatre ever built. The Colosseum is situated just east of the Roman Forum. Construction began under the emperor Vespasian in 72 AD,[2] and was completed in 80 AD under his successor and heir Titus.[3] Further modifications were made during the reign of Domitian (81–96).[4] These three emperors are known as the Flavian dynasty, and the amphitheatre was named in Latin for its association with their family name (Flavius).', 11, '(http://justfunfacts.com/wp-content/uploads/2015/11/colosseum-rome-italy.jpg,f,t)', 0, 0, '{}');
INSERT INTO "Wonder" VALUES ('Great Wall of China', 'Ancient', '{""}', 'The Great Wall of China is a series of fortifications made of stone, brick, tamped earth, wood, and other materials, generally built along an east-to-west line across the historical northern borders of China to protect the Chinese states and empires against the raids and invasions of the various nomadic groups of the Eurasian Steppe. Several walls were being built as early as the 7th century bce;[2] these, later joined together and made bigger and stronger, are now collectively referred to as the Great Wall.[3] Especially famous is the wall built 220–206 bce by Qin Shi Huang, the first Emperor of China. Little of that wall remains. Since then, the Great Wall has on and off been rebuilt, maintained, and enhanced; the majority of the existing wall is from the Ming Dynasty.', 12, '(http://www.nouahsark.com/data/images/infocenter/culture/great_wall/qreat_wall_01.jpg,f,t)', 0, 0, '{}');
INSERT INTO "Wonder" VALUES ('Christ the Redeemer', 'Modern', '{"Cristo Redentor"}', 'Christ the Redeemer (Portuguese: Cristo Redentor, standard Brazilian Portuguese: [ˈkɾistu χedẽˈtoɾ], local dialect: [ˈkɾiʃtu ɦedẽˈtoɦ]) is an Art Deco statue of Jesus Christ in Rio de Janeiro, Brazil, created by French sculptor Paul Landowski and built by the Brazilian engineer Heitor da Silva Costa, in collaboration with the French engineer Albert Caquot. The face was created by the Romanian artist Gheorghe Leonida. The statue is 30 metres (98 ft) tall, not including its 8-metre (26 ft) pedestal, and its arms stretch 28 metres (92 ft) wide.[1][2]', 14, '(http://i.huffpost.com/gadgets/slideshows/333823/slide_333823_3335630_free.jpg,f,t)', 0, 0, '{}');


-- Completed on 2016-03-30 14:26:03 CEST

--
-- PostgreSQL database dump complete
--
